---
title: "Find and Share Stories using data"
format: html
---

​Imagine you work for a company that's been hired to clean out a very old one room ​warehouse full of antiques. ​Your manager says no one has used the building for decades and ​doesn't know what the owners used it for for over the years. ​You've been assigned to clean it out and create a detailed inventory of what you ​find inside so that the items can be sold at auction. ​The manager suspects they'll be interesting antiques inside. ​Since many items are covered by blankets, you don't know what the room contains. ​You start cleaning from one side of the room to the other and ​you keep a digital inventory of the items you find. ​As you explore, you find a pile of metal gears chains and ​connection parts of all different sizes and shapes. ​You count them and write metal parts 47. ​You also find five large metal sheets, 12 large tricycles and ​seven metal poles, among other things. ​As you write these new items, you start to wonder if they're related or not. ​

This simple example demonstrates how data professionals explore data and ​learn more about the stories and trends along the way. ​As you uncover and clean up what is in front of you. ​The individual parts and pieces within the data will start to tell a larger story.

Of course data requires a few extra techniques and ​practices that in the warehouse example. ​But the general idea is the same. ​

You'll need to make sense of raw data content by reordering categorizing and ​reshaping it. ​You'll find a lot of different terms in the world of this process. *​Data wrangling* *data remediation,* *data munching* and *data cleaning*. ​They're all the most common. ​We combine all of these practices into a familiar term that most data ​professionals are familiar with:

# **Exploratory data analysis or EDA**. ​

**Exploratory data analysis or EDA is the process of investigating, ​organizing and analyzing data sets. ​And summarizing their main characteristics often employing data wrangling and ​visualization methods.**

**​**The six main practices of EDA are **discovering, structuring, ​cleaning, joining, validating and presenting.**

​These practices do not necessarily have to go in this order. ​And depending on the needs of the data team and ​the type of data they study they may perform EDA in different ways. ​

You'll also find that often the EDA process is iterative which means you'll go ​through the six practices multiple times in no particular ​order to prepare the data for further us.

​Let's spend time on each of the six practices, so ​that you have a better idea of what I mean. ​

## Discovering

Discovering is typically EDA first practice. ​During this practice, data professionals familiarize themselves with the data so ​they can start conceptualizing how to use it. ​They review the data and ask questions about it. ​During this phase data professionals may ask what are the column headers and ​what do they mean? ​How many total data points are there? ​In the example of the old warehouse at the beginning of the video the discovering ​practice might involve walking through the room. ​And removing coverings to get an idea of the amount and types of items.

## Structuring

​After some initial discovering the next step is to start organizing, ​this EDA practice is called structuring. ​Structuring is the process of taking raw data and organizing or ​transforming it to be more easily visualized, explained or modeled. ​Structuring refers to categorizing and ​organizing data columns based on the data already in the data set. ​In terms of the calendar data for example it might look like ​categorizing data into months or quarters rather than years. ​From the old warehouse analogy, ​structuring could be categorizing the items into metal and ​non metal categories and getting a total count for each type. ​

Before we move to the next practice of EDA, ​let's take a moment to talk about bias.

​Bias in the context of data structuring is organizing data in groupings categories or ​variables that don't accurately represent the whole data set. ​Most experts would agree that eliminating all bias from how data is structured is ​almost impossible. ​Because each person's individual ideas, training and experiences are different. ​As professionals however it's important to try to avoid bias while structuring data. ​

For example imagine you want to know what percent of the population has ​a college degree in the UK. ​But your model data only contains London residents. ​The data would be considered bias until you add data from the rest of the UK.

## Data cleaning​

The next EDA practice is data cleaning. ​Cleaning is the process of removing errors that may distort your data or ​make it less useful. ​Missing values, misspellings, duplicate entries or extreme outliers are all ​fairly common issues that need to be addressed during the data set cleaning. ​

## Joining

We'll move to another practice called joining. ​Joining is the process of augmenting or ​adjusting data by adding values from other data sets. ​In other words, you might add more value or ​context to the data by adding more information from other data sources. ​For example, you might find during the discovering structuring. ​Or cleaning processes that the data set doesn't have enough data for ​you to complete a specific project. ​In that case you should enrich the data by adding more to it. ​As an example remember when I talked about the UK and ​college degrees to help understand bias. ​In that instance, joining would be adding the data from the rest of ​the UK rather than just including data on London residents. ​

## Validating

Next on the list of EDA practices is validating. ​Validating refers to the process of verifying that the data is consistent and ​high quality. ​Validating data is the process for checking for misspellings and ​inconsistent number or date formats. ​And checking that the data cleaning process didn't introduce more errors. ​Data professionals typically use digital tools such as R, JavaScript or ​python to check for inconsistencies and errors in a data set and its data types. ​

## Presenting

The last EDA practice is presenting. ​Presenting involves making your cleaned data set or ​data visualizations available to others for analysis or further modeling. ​In other words presenting practice is sharing what you've learned through EDA. ​And asking for feedback whether in the form of a clean data set or ​data visualization. ​

We will be using the term data visualization a lot. ​To be clear a data visualization is a graph chart diagram or ​dashboard that is created as a representation of information. ​You might think that presenting always comes at the end of the EDA process. ​However presenting can come at any point in the EDA. ​Data visualizations aren't exclusive to the presenting practice. ​They should be used throughout the EDA. ​They help you understand data and point out trends and insights to others. ​

​In the workplace as a data professional presenting might look like preparing ​visuals and a slide presentation to share with your team. ​As you begin to plan your presentation, you should consider people with visual or ​auditory impairments by providing robust descriptions of the data. ​You can use things like all text descriptive text or captioned recording of ​the data so that your audience can explore the data themselves.

------------------------------------------------------------------------

​We will cover each of the EDA practices in detail later on. ​But one of the most important things to learn about the process is to ​ensure your EDA work does not misrepresent the data itself. ​The story you uncover should come from the data, ​not from your mind or biases in the data. ​It is your duty to convey your data in both an ethical and accessible way. ​

​In the workplace communicating data ethically would be presenting sales ​numbers in context year over year. ​So that rises and falls don't appear exaggerated in data visualizations. ​\\

------------------------------------------------------------------------

# Case Study. Deloitte

You’ve learned the definitions for each of the six practices of exploratory data analysis (EDA) — discovering, structuring, cleaning, joining, validating, and presenting. Next, you’ll discover how these practices apply to the data career space. In the following case study, members of Deloitte’s data team utilized the six practices of EDA to meet their client’s metrics and dashboarding needs. After you read more about the experiences of Deloitte’s team, you will have a tangible example of just how useful and empowering the application of these practices can be. 

## Get to know Deloitte

[Deloitte](https://www2.deloitte.com/us/en.html) is an audit, consulting, tax, and advisory service. The company has over 100,000 employees and partners around the globe, and they work with many of the world’s biggest companies. Their services range from tax and accounting solutions to artificial intelligence and cyber security risk programs. 

The multinational corporation’s business to business (B2B) model keeps their focus on working with their customers on a number of strategic and financial fronts, according to their individual needs.[Deloitte provides a range of services for client projects](https://youtu.be/8Gg5BsFexOU?list=PLl4by_vVwv0zjE2FRD7BMwI2lpaMCAgHh), such as auditing, consulting, financial advisory, risk advisory, taxes, data analysis, and regulation. Since 2008, Deloitte has made it their vision to be the standard of excellence in professional business services. Because of this focus, Deloitte has remained at the forefront of technology advancements, including the deployment of real-time metrics for their clients. 

In just one of their many success stories,  Deloitte recently helped a billion-dollar cloud-based analytics and software company streamline the tracking and organization of their marketing leads and strategic analysis of their performance data. In this reading, you will see how Deloitte used EDA to analyze the client’s data in order to propose and apply a comprehensive solution they still use today.    

## The challenges 

One of Deloitte’s most important cloud-based software solution clients was facing a variety of challenges with their marketing and performance data. They asked Deloitte for help on all of them. Here are the specific challenges the client presented to Deloitte:  

-   Difficulty in following up on marketing leads 

-   Struggling to promptly track their marketing campaign performance

-   A lack of personalized data dashboards displaying strategic company metrics

### **Following up on marketing leads**

Deloitte’s client offers a range of cloud-based analysis services and software products to businesses around the globe, making it a monumental task to follow up on each of the thousands of inquiries and potential sales leads they receive on a monthly basis. As a result, Deloitte’s client was seeking a solution to help them more adequately track and act on these leads.   

### **Tracking marketing campaign performance**

Relying on just four data analysts for analysis of marketing campaign performance for a \$1B multinational corporation was quickly becoming unsustainable. Before Deloitte stepped in to help, the client’s performance tracking system was a series of data tables updated manually and kept in a spreadsheet tab. Each region kept their own performance data, creating issues of consistency and hours of wasted energy for the analysts who had to compile and merge the data to get a corporation-wide performance picture.  

### **Personalizing data dashboards**

Because of differing needs for each level of management and varying marketing regions across the globe, the client needed to be able to easily parse and group data specific to their employees' needs across the corporation. Because they were working off of multiple spreadsheets across several different departments and locales, the client found they could not easily filter the data according to their needs, and therefore were not able to adequately shift strategy to improve performance. 

## The approach  

As Deloitte began working with their new client, they designed an approach that would meet each of their client’s proposed needs. Refer to the following PACE entries to review this approach in detail.

## Plan 

To begin, Deloitte needed to meet with client stakeholders and help develop their vision for the future according to the three areas mentioned above: **Marketing leads, measuring marketing campaign performance,** and **personalizing data dashboards.** 

They needed to understand the client’s business by learning its processes, objectives and key results (OKRs), and how it approached and used its customer and potential customer data. 

Key project milestones were established early on, and adjusted according to any new knowledge acquired. Those milestones were: 

-   Alignment with client on the future vision of data architecture and dashboards

-   Establishment of the new data architecture

-   Launch of descriptive and diagnostic tooling

-   Launch of predictive models

-   Training the global sales team on new tooling

Deloitte determined that their project plan would begin with the discovering, structuring, and cleaning practices of EDA on the client’s company-wide performance data.  

Deloitte quickly learned what OKRs the client wanted easy access to once the personalized dashboards were complete and set plans to achieve that outcome. Those OKRs came in the form of the following questions: 

-   How much revenue was earned from a particular marketing campaign? 

-   What industry, region, sector, and company size did the new customer fall into? 

-   How long did it take to finalize the sale after the initial point of contact? 

-   What was the success rate of different types of campaigns (i.e., in person events vs. online webinars)? 

-   What was the average cost of marketing per customer gained?

## Analyze

As part of the framing of their initial analysis of the client’s data, it became clear the client was unfamiliar with Deloitte’s product services offerings, including assets like easy-to-use Tableau dashboard tooling. Because of this, the client’s assumptions and requests for what was possible fell far below Deloitte’s actual capability. This represented an opportunity to not only meet, but actually exceed the client’s expectations of the project. 

The first challenges of analysis were in understanding where the data was coming from and what each data variable meant. The client used non-standard naming conventions and definitions in their data, so Deloitte had to use discovering practices to learn their language to fully understand the client’s data and plan for how to help them use it. 

Deloitte found that the client’s approach to tracking performance at the time was clunky and overbroad at best. The performance data they gathered consisted of the use of overall averages to determine value of strategic company-wide actions. Without specific performance data per region, the company had no simple way of tracking regional performance.  

-   As an example of the client’s overbroad data tracking at the time, this was the formula they used to derive the average revenue they gained per marketing campaign.

Deloitte learned that the client’s internal marketing and sales teams were organized according to geographic regions, industries, and customer account size. Regional leads had the authority and autonomy to conduct marketing research and campaigns on their own, but did take guidance and occasional instruction from the global team. Deloitte’s analysts began structuring the data in a consistent way company wide as part of their EDA of the client’s data.

In terms of customer life cycle, Deloitte learned that the client’s marketing leads would generate marketing campaigns and then inform sales partners in their regions. Field sales representatives would follow up on all leads generated from the campaigns, and they would also network outside of existing campaigns to find additional customers. This discovering part of EDA informed Deloitte’s team on more specific and plausible solutions that could meet the client’s needs. 

The Deloitte team used discovering and structuring practices of EDA in spreadsheets to review all of the existing data from the client’s Salesforce and marketing campaigns. They began to identify and define every data variable that existed in their client’s sales system. Once an inventory of data variables was structured, cleaned, and validated, the Deloitte team brainstormed the type of insights they could glean from the information. 

After the review, Deloitte utilized the presenting practice of EDA to share the information they had gathered with the client. They listened and asked questions to get a better understanding of how the client viewed their own business and what factors were important to them according to the data.  

## Construct

From their analysis of the client’s systems and the discovering, structuring, and cleaning practices of EDA they did on the client’s performance data, Deloitte learned that the client needed a total overhaul of their analytical process; one that provided much greater detail and allowed them to identify and address bottlenecks, unprofitable campaigns, and unproductive customer segments.

With the client’s approval, Deloitte completely rebuilt the client’s data internal infrastructure from the ground up to make analysis more streamlined.  

On top of the infrastructure overhaul, the most hands-on solution for the client was to build customized and dynamic dashboards for specific stakeholders. 

-   The Deloitte team worked with each client stakeholder group to understand their needs and their OKRs. 

-   They then helped develop tailored solutions for the client by creating supporting collateral resources, such as a data dictionary to define what each variable represents and how it should and should not be used. 

Deloitte used the information they gathered from their client’s data to build automations and tools that performed predictive analysis on their OKRs. This allowed the client to establish feasible, but aggressive targets for the future.

## Execute

Deloitte’s overhaul of their client’s data infrastructure led to a streamlined, tiered approach to global data gathering. Where before the client was forced to rely on regionally gathered and inconsistently structured spreadsheets to formulate their performance metrics, they could now easily quantify everything from global, company-wide performance down to the performance of a regional team of sales team members on specific products and subset of clients.

After implementation of personalized dashboards, Senior VPs could filter the status and performance of the OKRs to the whole departments and regions for which they were responsible. Additionally, regional leads, marketing leads, and even local sales leads were able to view data filtered down to their applicable area. 

As part of implementation, Deloitte team members created training sessions according to their client’s needs across the organization—everything from how to use the personalized dashboards to how to maintain the new data infrastructure.  

The Deloitte-designed dashboards and data infrastructure instantly became valuable assets to multiple stakeholders across the client’s global team. 

**Note**: In their work with the client,Deloitte was not following the PACE workflow as it is listed above; rather, while documenting the details of their work into this case study, Deloitte’s work for the client has been organized according to the PACE workflow to demonstrate the versatility of its application. 

## Summarizing the results

When Deloitte started working with their new client, they were hesitant to trust the accuracy of the company’s existing data because of a lack of standardization between the marketing and sales teams. That lack of consistency made it difficult to associate any particular sale to a specific campaign. After a few weeks of studying the client’s sales and marketing processes and EDA of their data, Deloitte rebuilt the data infrastructure in a way that directly tied all sales to their applicable marketing campaigns. They tied these sales to marketing campaigns using primary keys aligned across a number of data tables that could be easily sorted. This gave the Deloitte analysts an idea of what was possible with the data and led them to building final products that exceeded what the client thought was initially possible.

Once the infrastructure was overhauled, Deloitte’s performance of EDA uncovered that the client was focusing too much effort on earning new clients, to the detriment of existing client relationships. While sales to new clients did increase because of the focus of OKRs, sales to their existing customers plummeted. This result was previously unknown to the client. As a result, the client was able to pivot their strategy by both sales region and product. The dynamic dashboards Deloitte created became the client’s most effective tool for measuring and tracking performance as well as setting strategy.  

## Conclusion

Because of Deloitte’s focus on the client’s business problem in both their assessment of the client’s business practices and EDA of their data, they were able to uncover truths previously hidden in unstructured data. Deloitte built interactive, dynamic data dashboards designed to filter down to any sales region or product in the company so that the client could discover these truths on their own in the future. The greatest benefit of these solutions was the client’s leadership and marketing leads became a much more agile team. They were better able to make effective business decisions that directly improved revenue. The data infrastructure overhaul and data dashboard solutions also helped improve the work-life balance of their analysts. All of these outcomes were notable for not only the client but also Deloitte because the client was and is a key partner and account for the firm. Because of their focus on the data, Deloitte was able to offer a solution that exceeded the client’s expectations and, in turn, helped them better serve their customers around the world.